name: canteengo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/canteengo.jpeg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/canteengo.jpeg"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/canteengo.jpeg